spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/database"
    driverClassName: "org.postgresql.Driver"
    username: "db_user"
    password: "db_pass"
  jpa:
    database: "POSTGRESQL"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
    hibernate:
      ddl-auto: "update"